# server:
#   ssl:
#     key-store: classpath:tomcat.keystore
#     key-store-password: 276364092
#     key-alias: tomcatKey
#     key-store-type: JKS
#     enabled: true
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/interaction_fields?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 276364092
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 276364092
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
  zipkin:
    base-url: http://127.0.0.1:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ash
    password: 276364092
    virtual-host: rabbit
    connection-timeout: 15000
    publisher-confirms: true
    listener:
      ack-mode: manual
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000
logging:
  level:
    root: info
    org.ktorm: debug
